export const DataTypes = { PRODUCTS: "products", CATEGORIES: "categories" };
export const ActionTypes = {
    DATA_LOAD: "DATA_LOAD",
    DATA_SET_SORT_PROPERTY: "DATA_SET_SORT_PROPERTY",
    DATA_SET_PAGESIZE: "DATA_SET_PAGESIZE",
    CART_ADD: "CART_ADD",
    CART_UPDATE: "CART_UPDATE",
    CART_REMOVE: "CART_REMOVE",
    CART_CLEAR: "CART_CLEAR",
};
